<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\NostalgiaServer.ico</ApplicationIcon>
    <AssemblyName>NostalgiaServer</AssemblyName>
    <RootNamespace>NostalgiaServer</RootNamespace>
    <Version>1.0.0</Version>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <Target Name="CopyToNostalgia" AfterTargets="Publish">
    <Copy SourceFiles="$(PublishDir)$(AssemblyName).exe" DestinationFolder="G:\vmangos_KI\Nostalgia\" />
  </Target>
</Project>
