LoadFile "../PHP/libcrypto-3-x64.dll"
LoadFile "../PHP/libssl-3-x64.dll"
LoadModule php_module "../PHP/php8apache2_4.dll"
PHPIniDir "../PHP"
<IfModule mime_module>
    AddType application/x-httpd-php .php
</IfModule>
